# This is a basic workflow to help you get started with Actions

name: Tag AWS Resources - Keep til the weekend

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      nameToTag:
        type: string
        description: the key of resource(s) you would like to tag in AWS

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-run-cloud-custodian:
    name: Run Cloud Custodian to tag AWS resources
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install python3-venv -y
          python3 -m venv custodian
          source custodian/bin/activate
          pip install c7n
          pip install c7n_azure
          pip install c7n_gcp
          pip install c7n-mailer
      - name: update yaml files with user reserved names
        env: 
          USER_KEYS: ${{ inputs.nameToTag }}
        run: | 
          date
          cd qa-custodian
          for i in `ls *.yaml`; do cat $i | sed -e 's/USERKEYS/'"$USER_KEYS"'/g' -i $i; done
      - name: run cloud custodian
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          source custodian/bin/activate
          cd qa-custodian
          while read -r line; do custodian run --output-dir=. --region=$line --dry-run add-friday-tags.yaml; done < regions.txt
